---
- name: "Pulling Docker images"
  community.docker.docker_image_pull:
    name: "{{ item.name }}"
  loop:
    - {name: 'leonjza/gowitness'}
    - {name: 'snovvcrash/divideandscan'}
    - {name: 'rustscan/rustscan'}
    - {name: 'cablethief/sshaft'}
    - {name: 'portswigger/sig2n'}
    - {name: 'bettercap/bettercap'}
  become: true

- name: "Running Docker Compose"
  community.docker.docker_compose_v2:
    project_src: "{{ ansible_env.HOME }}/Downloads/BHCE"
  become: true