---
- include_tasks: pre-install.yml
- include_tasks: apt.yml
- include_tasks: python.yml
- include_tasks: go.yml
#- include: gem-tools.yml
- include_tasks: docker.yml
- include_tasks: github.yml
- include_tasks: other.yml
- include_tasks: post-install.yml
