---
  - name: "Updating Nmap's ScriptDB"
    shell: "nmap --script-updatedb"
    become: true

  - name: "Modifying /etc/proxychains4.conf"
    lineinfile:
      path: /etc/proxychains4.conf
      search_string: "socks4 	127.0.0.1 9050"
      line: "socks5 127.0.0.1 1080"
    become: true

  - name: "Disabling tailscale on startup"
    systemd_service:
      name: tailscaled
      enabled: false
    become: true

  - name: "Starting Nxc for the first time"
    shell: "nxc"
    ignore_errors: true
    no_log: true

  - name: "Modifying nxc configuration file"
    copy:
      src: "files/nxc.conf"
      dest: "{{ ansible_env.HOME }}/.nxc/nxc.conf"