---
- name: "Customizing Kali"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/configure-system"
    - role: "roles/install-system-tools"
    - role: "roles/customize-terminal"
#    - role: "roles/configure-logging"
    - role: "roles/install-tools"
      users:
        - username: "{{ ansible_user_id }}" 