---
  - name: "Downloading .NET 8.0 Runtime (v.8.0.11)"
    get_url:
      url: https://download.visualstudio.microsoft.com/download/pr/805cdca8-ac43-4d76-8ce8-efd11f1997f2/17aeb8b0cd34c6f8d80217bf6a4ed3cd/dotnet-runtime-8.0.11-linux-x64.tar.gz
      dest: "{{ ansible_env.HOME }}/Downloads/dotnet.tar.gz"

  - name: "Extracting .NET"
    unarchive:
      src: "{{ ansible_env.HOME }}/Downloads/dotnet.tar.gz"
      dest: "{{ ansible_env.HOME }}/Downloads/dotnet"
      remote_src: true