---
- name: "Preparing Docker Installation"
  block:
    - name: "Downloading key"
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
      become: true

    - name: "Adding repository"
      apt_repository:
        repo: "deb https://download.sublimetext.com/ apt/stable/"
        filename: sublime-text
      become: true

    - name: "Updating apt cache"
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      become: true
      become_method: sudo

- name: "Installing Sublime"
  package:
    name:
      - sublime-text
    state: latest
  become: true
