---
- name: Create necessary directories
  file:
    path: "{{ item.name }}"
    state: "{{ item.type }}"
  loop:
    - { name: "{{ ansible_env.HOME }}/Pentest", type: "directory"}
    - { name: "{{ ansible_env.HOME }}/Pentest/Logs", type: "directory"}
    - { name: "{{ ansible_env.HOME }}/Pentest/Scope", type: "directory"}
    - { name: "{{ ansible_env.HOME }}/Pentest/Report", type: "directory"}
    - { name: "{{ ansible_env.HOME }}/Pentest/Scans", type: "directory"}
    - { name: "{{ ansible_env.HOME }}/Pentest/Scans/Nxc", type: "directory"}
    - { name: "{{ ansible_env.HOME }}/Pentest/Scans/Nmap", type: "directory"}
    - { name: "{{ ansible_env.HOME }}/Pentest/Loot", type: "directory"}
    - { name: "{{ ansible_env.HOME }}/Pentest/Loot/DCSync", type: "directory"}
    - { name: "{{ ansible_env.HOME }}/Pentest/Loot/Creds", type: "directory"}
    - { name: "{{ ansible_env.HOME }}/vmware-shared", type: "directory"}

- name: Copy over files
  copy:
    src: "{{ role_path }}/files/{{ item.filename }}"
    dest: "{{ ansible_env.HOME }}"
    mode: preserve
  loop:
    - {filename: "remove-history.sh"}
    - {filename: "tmux_start_logging.sh"}
    - {filename: "ad-recon.sh"}