---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: Remove /usr/lib/firmware/intel/sof-ace-tplg # Probably a temporary issue
  file:
    path: /usr/lib/firmware/intel/sof-ace-tplg
    state: absent
  become: true

- name: "Upgrade all packages"
  apt: upgrade=dist force_apt_get=yes
  become: true
  become_method: sudo

- name: "Remove unused dependancies"
  apt: autoremove=true force_apt_get=yes
  become: true
  become_method: sudo